### ISSUE TITLE
Theoretical explanations

### ISSUE THREAD

**Issue by ziemerz** [radeonxray/UFO-Exam#5]
Score: 9
This is not really a theoretical article, but way more practical, which means this is difficult to rate. The theoretical explanations that are there, are quite well explained, but the article feels like it's targeting an audience that are already well acquainted with JavaScript. Words like "bundler" is not explained.

Other than that, I feel that the explanation is quite good and well defined.

**Comment by radeonxray** [comment]
How we adressed the issue:
- We've removed the section/mention of the "tree shaking" feature, due to realization, that its more of a genral ECMAScript2015-feature, rather than a TypeScript one. Because of this removal, the mention of "the bundler" has also been removed 91b833a

- We agree that there is a lack of theoratical explanations, but because of the subject and lack of theories, we have  relied on our detailed examples and practical experience.
